# Copyright (C) 2025 Eclipse Foundation and others.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Public License v. 2.0 which is available at
# http://www.eclipse.org/legal/epl-2.0.
#
# SPDX-FileType: SOURCE
# SPDX-FileCopyrightText: 2025 Eclipse Foundation
# SPDX-License-Identifier: EPL-2.0

# Please note that the specific tsffer configuration in the steps below is primarily chosen to illustrate different usage scenarios;
# this is not necessarily reflecting a best-of-breed configuration.

---
# .github/workflows/release.yml
name: Release workflow

on:
  push:
    tags:
      - v*

concurrency:
  group: "release-${{ github.head_ref || github.ref }}"
  cancel-in-progress: true

jobs:
  quality_artifacts:
    name: A job to collect quality artifacts
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print run ID
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh run view $GITHUB_RUN_ID

      # Do the quality artifact collection thing
      - name: Upload README to release
        uses: svenstaro/upload-release-action@v2
        id: upload_readme
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: README.md
          tag: ${{ github.ref }}

      - name: Collect README artifact
        uses: ./
        id: tsffer_README
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: reference
          reference_properties: |
            {
              "reference_type": "download_url",
              "url": "${{ steps.upload_readme.outputs.browser_download_url }}"
            }
          asset_description: "For illustration purposes, we are providing a link to our README in the release artifacts"
          asset_name: "Project README"
          asset_tsf_ids: "TA-BEHAVIOURS"

      - name: Collect fourth quality artifact, a reference to this workflow (upload to release set)
        uses: ./
        id: tsffer_reference_list
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: reference
          release_upload: true
          reference_properties: |
            [
              {
                "reference_type": "github",
                "repository": "${{ github.repository }}",
                "path": ".github/workflows/release.yml#L11",
                "public": true,
                "ref": "${{ github.ref_name }}"
              },
              {
                "reference_type": "webpage",
                "url": "https://www.example.org"
              }
            ]
          asset_description: "Link to specific line in tsffer release automation"
          asset_name: "ReleaseCI"
          asset_tsf_ids: "TA-RELEASES,TA-ITERATIONS"

  artifacts_upload:
    name: Upload quality artifact archive to release file set
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: read
    needs: quality_artifacts
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create release
        uses: softprops/action-gh-release@v2
        id: create_release
      - name: Show release URL
        run: |
          echo ${{ steps.create_release.outputs.url }}

      - name: Package quality artifacts and upload to release
        uses: ./
        id: tsffer_package
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          mode: package
          release_upload: true
